// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	DeviceID          string             `json:"device_id"`
	Platform          string             `json:"platform"`
	PushToken         []byte             `json:"push_token"`
	UpstreamHost      string             `json:"upstream_host"`
	UpstreamPort      int32              `json:"upstream_port"`
	UpstreamTransport string             `json:"upstream_transport"`
	UpstreamUser      string             `json:"upstream_user"`
	UpstreamPassword  []byte             `json:"upstream_password"`
	UpstreamRealm     pgtype.Text        `json:"upstream_realm"`
	DisplayName       pgtype.Text        `json:"display_name"`
	B2buaSipUser      string             `json:"b2bua_sip_user"`
	DeviceContact     pgtype.Text        `json:"device_contact"`
	PushProvider      pgtype.Text        `json:"push_provider"`
	PushParam         pgtype.Text        `json:"push_param"`
	PushPrid          pgtype.Text        `json:"push_prid"`
	RegisteredAt      pgtype.Timestamptz `json:"registered_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	LastSeen          pgtype.Timestamptz `json:"last_seen"`
}

type PendingCall struct {
	CallID     string             `json:"call_id"`
	DeviceID   string             `json:"device_id"`
	SipCallID  string             `json:"sip_call_id"`
	SipFrom    string             `json:"sip_from"`
	SipTo      string             `json:"sip_to"`
	SdpOffer   pgtype.Text        `json:"sdp_offer"`
	CallerUri  string             `json:"caller_uri"`
	CallerName pgtype.Text        `json:"caller_name"`
	State      string             `json:"state"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

type Setting struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

type User struct {
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
