// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingCall = `-- name: CreatePendingCall :exec
INSERT INTO pending_calls (
    call_id, device_id, sip_call_id, sip_from, sip_to,
    sdp_offer, caller_uri, caller_name, state, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type CreatePendingCallParams struct {
	CallID     string             `json:"call_id"`
	DeviceID   string             `json:"device_id"`
	SipCallID  string             `json:"sip_call_id"`
	SipFrom    string             `json:"sip_from"`
	SipTo      string             `json:"sip_to"`
	SdpOffer   pgtype.Text        `json:"sdp_offer"`
	CallerUri  string             `json:"caller_uri"`
	CallerName pgtype.Text        `json:"caller_name"`
	State      string             `json:"state"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePendingCall(ctx context.Context, arg CreatePendingCallParams) error {
	_, err := q.db.Exec(ctx, createPendingCall,
		arg.CallID,
		arg.DeviceID,
		arg.SipCallID,
		arg.SipFrom,
		arg.SipTo,
		arg.SdpOffer,
		arg.CallerUri,
		arg.CallerName,
		arg.State,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (username, password_hash, role)
VALUES ($1, $2, $3)
ON CONFLICT (username) DO NOTHING
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Username, arg.PasswordHash, arg.Role)
	return err
}

const deleteDeviceByID = `-- name: DeleteDeviceByID :exec
DELETE FROM devices WHERE device_id = $1
`

func (q *Queries) DeleteDeviceByID(ctx context.Context, deviceID string) error {
	_, err := q.db.Exec(ctx, deleteDeviceByID, deviceID)
	return err
}

const deletePendingCall = `-- name: DeletePendingCall :exec
DELETE FROM pending_calls WHERE call_id = $1
`

func (q *Queries) DeletePendingCall(ctx context.Context, callID string) error {
	_, err := q.db.Exec(ctx, deletePendingCall, callID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE username = $1
`

func (q *Queries) DeleteUser(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, deleteUser, username)
	return err
}

const getDeviceByB2BUASIPUser = `-- name: GetDeviceByB2BUASIPUser :one
SELECT device_id, platform, push_token, upstream_host, upstream_port, upstream_transport, upstream_user, upstream_password, upstream_realm, display_name, b2bua_sip_user, device_contact, user_agent, push_provider, push_param, push_prid, registered_at, expires_at, last_seen, disabled FROM devices WHERE b2bua_sip_user = $1 AND disabled = false LIMIT 1
`

func (q *Queries) GetDeviceByB2BUASIPUser(ctx context.Context, b2buaSipUser string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByB2BUASIPUser, b2buaSipUser)
	var i Device
	err := row.Scan(
		&i.DeviceID,
		&i.Platform,
		&i.PushToken,
		&i.UpstreamHost,
		&i.UpstreamPort,
		&i.UpstreamTransport,
		&i.UpstreamUser,
		&i.UpstreamPassword,
		&i.UpstreamRealm,
		&i.DisplayName,
		&i.B2buaSipUser,
		&i.DeviceContact,
		&i.UserAgent,
		&i.PushProvider,
		&i.PushParam,
		&i.PushPrid,
		&i.RegisteredAt,
		&i.ExpiresAt,
		&i.LastSeen,
		&i.Disabled,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT device_id, platform, push_token, upstream_host, upstream_port, upstream_transport, upstream_user, upstream_password, upstream_realm, display_name, b2bua_sip_user, device_contact, user_agent, push_provider, push_param, push_prid, registered_at, expires_at, last_seen, disabled FROM devices WHERE device_id = $1 LIMIT 1
`

func (q *Queries) GetDeviceByID(ctx context.Context, deviceID string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, deviceID)
	var i Device
	err := row.Scan(
		&i.DeviceID,
		&i.Platform,
		&i.PushToken,
		&i.UpstreamHost,
		&i.UpstreamPort,
		&i.UpstreamTransport,
		&i.UpstreamUser,
		&i.UpstreamPassword,
		&i.UpstreamRealm,
		&i.DisplayName,
		&i.B2buaSipUser,
		&i.DeviceContact,
		&i.UserAgent,
		&i.PushProvider,
		&i.PushParam,
		&i.PushPrid,
		&i.RegisteredAt,
		&i.ExpiresAt,
		&i.LastSeen,
		&i.Disabled,
	)
	return i, err
}

const getDevicesByUpstreamUser = `-- name: GetDevicesByUpstreamUser :many
SELECT device_id, platform, push_token, upstream_host, upstream_port, upstream_transport, upstream_user, upstream_password, upstream_realm, display_name, b2bua_sip_user, device_contact, user_agent, push_provider, push_param, push_prid, registered_at, expires_at, last_seen, disabled FROM devices WHERE upstream_user = $1
`

func (q *Queries) GetDevicesByUpstreamUser(ctx context.Context, upstreamUser string) ([]Device, error) {
	rows, err := q.db.Query(ctx, getDevicesByUpstreamUser, upstreamUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.DeviceID,
			&i.Platform,
			&i.PushToken,
			&i.UpstreamHost,
			&i.UpstreamPort,
			&i.UpstreamTransport,
			&i.UpstreamUser,
			&i.UpstreamPassword,
			&i.UpstreamRealm,
			&i.DisplayName,
			&i.B2buaSipUser,
			&i.DeviceContact,
			&i.UserAgent,
			&i.PushProvider,
			&i.PushParam,
			&i.PushPrid,
			&i.RegisteredAt,
			&i.ExpiresAt,
			&i.LastSeen,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingCall = `-- name: GetPendingCall :one
SELECT call_id, device_id, sip_call_id, sip_from, sip_to, sdp_offer, caller_uri, caller_name, state, created_at, expires_at FROM pending_calls WHERE call_id = $1 LIMIT 1
`

func (q *Queries) GetPendingCall(ctx context.Context, callID string) (PendingCall, error) {
	row := q.db.QueryRow(ctx, getPendingCall, callID)
	var i PendingCall
	err := row.Scan(
		&i.CallID,
		&i.DeviceID,
		&i.SipCallID,
		&i.SipFrom,
		&i.SipTo,
		&i.SdpOffer,
		&i.CallerUri,
		&i.CallerName,
		&i.State,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const getUser = `-- name: GetUser :one
SELECT username, password_hash, role, created_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT username, role, created_at FROM users ORDER BY created_at DESC
`

type ListUsersRow struct {
	Username  string             `json:"username"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.Username, &i.Role, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneDevices = `-- name: PruneDevices :exec
DELETE FROM devices WHERE expires_at < $1
`

func (q *Queries) PruneDevices(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, pruneDevices, expiresAt)
	return err
}

const prunePendingCalls = `-- name: PrunePendingCalls :exec
DELETE FROM pending_calls WHERE expires_at < $1
`

func (q *Queries) PrunePendingCalls(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, prunePendingCalls, expiresAt)
	return err
}

const setDeviceDisabled = `-- name: SetDeviceDisabled :exec
UPDATE devices SET disabled = $2 WHERE device_id = $1
`

type SetDeviceDisabledParams struct {
	DeviceID string `json:"device_id"`
	Disabled bool   `json:"disabled"`
}

func (q *Queries) SetDeviceDisabled(ctx context.Context, arg SetDeviceDisabledParams) error {
	_, err := q.db.Exec(ctx, setDeviceDisabled, arg.DeviceID, arg.Disabled)
	return err
}

const updateDeviceContact = `-- name: UpdateDeviceContact :exec
UPDATE devices SET device_contact = $2, user_agent = $3, last_seen = NOW() WHERE b2bua_sip_user = $1
`

type UpdateDeviceContactParams struct {
	B2buaSipUser  string      `json:"b2bua_sip_user"`
	DeviceContact pgtype.Text `json:"device_contact"`
	UserAgent     pgtype.Text `json:"user_agent"`
}

func (q *Queries) UpdateDeviceContact(ctx context.Context, arg UpdateDeviceContactParams) error {
	_, err := q.db.Exec(ctx, updateDeviceContact, arg.B2buaSipUser, arg.DeviceContact, arg.UserAgent)
	return err
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :exec
UPDATE devices SET last_seen = NOW() WHERE b2bua_sip_user = $1
`

func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, b2buaSipUser string) error {
	_, err := q.db.Exec(ctx, updateDeviceLastSeen, b2buaSipUser)
	return err
}

const updatePendingCallState = `-- name: UpdatePendingCallState :exec
UPDATE pending_calls SET state = $2 WHERE call_id = $1
`

type UpdatePendingCallStateParams struct {
	CallID string `json:"call_id"`
	State  string `json:"state"`
}

func (q *Queries) UpdatePendingCallState(ctx context.Context, arg UpdatePendingCallStateParams) error {
	_, err := q.db.Exec(ctx, updatePendingCallState, arg.CallID, arg.State)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE username = $1
`

type UpdateUserPasswordParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Username, arg.PasswordHash)
	return err
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO devices (
    device_id, platform, push_token, upstream_host, upstream_port,
    upstream_transport, upstream_user, upstream_password, upstream_realm,
    display_name, b2bua_sip_user, device_contact, user_agent, push_provider,
    push_param, push_prid, expires_at, last_seen
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
ON CONFLICT (device_id) DO UPDATE SET
    platform = EXCLUDED.platform,
    push_token = EXCLUDED.push_token,
    upstream_host = EXCLUDED.upstream_host,
    upstream_port = EXCLUDED.upstream_port,
    upstream_transport = EXCLUDED.upstream_transport,
    upstream_user = EXCLUDED.upstream_user,
    upstream_password = EXCLUDED.upstream_password,
    upstream_realm = EXCLUDED.upstream_realm,
    display_name = EXCLUDED.display_name,
    b2bua_sip_user = EXCLUDED.b2bua_sip_user,
    device_contact = EXCLUDED.device_contact,
    user_agent = EXCLUDED.user_agent,
    push_provider = EXCLUDED.push_provider,
    push_param = EXCLUDED.push_param,
    push_prid = EXCLUDED.push_prid,
    expires_at = EXCLUDED.expires_at,
    last_seen = EXCLUDED.last_seen
`

type UpsertDeviceParams struct {
	DeviceID          string             `json:"device_id"`
	Platform          string             `json:"platform"`
	PushToken         []byte             `json:"push_token"`
	UpstreamHost      string             `json:"upstream_host"`
	UpstreamPort      int32              `json:"upstream_port"`
	UpstreamTransport string             `json:"upstream_transport"`
	UpstreamUser      string             `json:"upstream_user"`
	UpstreamPassword  []byte             `json:"upstream_password"`
	UpstreamRealm     pgtype.Text        `json:"upstream_realm"`
	DisplayName       pgtype.Text        `json:"display_name"`
	B2buaSipUser      string             `json:"b2bua_sip_user"`
	DeviceContact     pgtype.Text        `json:"device_contact"`
	UserAgent         pgtype.Text        `json:"user_agent"`
	PushProvider      pgtype.Text        `json:"push_provider"`
	PushParam         pgtype.Text        `json:"push_param"`
	PushPrid          pgtype.Text        `json:"push_prid"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	LastSeen          pgtype.Timestamptz `json:"last_seen"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.Exec(ctx, upsertDevice,
		arg.DeviceID,
		arg.Platform,
		arg.PushToken,
		arg.UpstreamHost,
		arg.UpstreamPort,
		arg.UpstreamTransport,
		arg.UpstreamUser,
		arg.UpstreamPassword,
		arg.UpstreamRealm,
		arg.DisplayName,
		arg.B2buaSipUser,
		arg.DeviceContact,
		arg.UserAgent,
		arg.PushProvider,
		arg.PushParam,
		arg.PushPrid,
		arg.ExpiresAt,
		arg.LastSeen,
	)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
